---
title: The Best Headphones
baseurl: "/"
permalink: "/:title/"
palette: orange
header:
  title: The Best Headphones
  logo_img: ''
  has_nav: true
  menu:
    actions: []
footer:
  logo_img: images/logo_alt.png
  tagline: Headphone Reviews By Chris Lema
  has_nav: true
  nav_title: Menu
  has_social: true
  social_title: Find me online
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Get the latest reviews in your inbox
  content: "&copy; Chris Lema. All rights reserved."
  links:
  - text: Stackbit. Jeykyll. Forestry.io. Netlify
    url: https://chrislema.com
    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
